### ISSUE TITLE
POST 方法报错

### ISSUE THREAD

**Issue by hrscy** [HouWan/HWNetworking#1]
HN.POST(url: "test", parameters: ["user_id": "1"]).success { (response) in
            
}.failed { (error) in

}
这个方法报错，原因在于 parameters: ["user_id": "1"]，调用这个方法会出现下面的错误：
![image](https://user-images.githubusercontent.com/16634163/86202670-7b37d800-bb95-11ea-8644-df9da3506085.png)

**Comment by HouWan** [comment]
谢谢你的`issue`，这是一个死循环bug，原因是`parameters `的参数类型造成的推断调用方法出现了问题，我已解决并提交了新的版本。
