### ISSUE TITLE
取消当前的请求

### ISSUE THREAD

**Issue by hrscy** [HouWan/HWNetworking#2]
可否添加一个方法，取消当前的正在请求的操作？

**Comment by hrscy** [comment]
`
HN.sessionManager.session.getAllTasks { (tasks) in
    tasks.forEach { $0.cancel() }
}
`

**Comment by hrscy** [comment]
``

**Comment by HouWan** [comment]
@hrscy 我改写了很多东西，最近会提交一次。

**Comment by hrscy** [comment]
@HouWan 
期待~！

**Comment by HouWan** [comment]
已更新，已经提交。话说你取消当前的请求，我已经加了`cancel()`方法了，包括取消当前所有的请求.都有的。

@hrscy
